export type Article = "der" | "die" | "das";

export interface Noun {
  id: string;
  word: string;
  article: Article;
  plural: string;
  translation: string;
  level: "A1" | "A2" | "B1" | "B2";
  topic: string;
}

export const nouns: Noun[] = [
  ["apfel", "Apfel", "der", "Äpfel", "apple", "A1", "Essen"],
  ["banane", "Banane", "die", "Bananen", "banana", "A1", "Essen"],
  ["brot", "Brot", "das", "Brote", "bread", "A1", "Essen"],
  ["kaese", "Käse", "der", "Käse", "cheese", "A1", "Essen"],
  ["milch", "Milch", "die", "—", "milk", "A1", "Essen"],
  ["wasser", "Wasser", "das", "—", "water", "A1", "Essen"],
  ["kaffee", "Kaffee", "der", "Kaffees", "coffee", "A1", "Essen"],
  ["suppe", "Suppe", "die", "Suppen", "soup", "A1", "Essen"],
  ["ei", "Ei", "das", "Eier", "egg", "A1", "Essen"],
  ["fisch", "Fisch", "der", "Fische", "fish", "A1", "Essen"],
  ["wohnung", "Wohnung", "die", "Wohnungen", "apartment", "A1", "Zuhause"],
  ["haus", "Haus", "das", "Häuser", "house", "A1", "Zuhause"],
  ["tisch", "Tisch", "der", "Tische", "table", "A1", "Zuhause"],
  ["lampe", "Lampe", "die", "Lampen", "lamp", "A1", "Zuhause"],
  ["fenster", "Fenster", "das", "Fenster", "window", "A1", "Zuhause"],
  ["stuhl", "Stuhl", "der", "Stühle", "chair", "A1", "Zuhause"],
  ["tuer", "Tür", "die", "Türen", "door", "A1", "Zuhause"],
  ["bett", "Bett", "das", "Betten", "bed", "A1", "Zuhause"],
  ["schrank", "Schrank", "der", "Schränke", "wardrobe", "A1", "Zuhause"],
  ["kueche", "Küche", "die", "Küchen", "kitchen", "A1", "Zuhause"],
  ["zimmer", "Zimmer", "das", "Zimmer", "room", "A1", "Zuhause"],
  ["garten", "Garten", "der", "Gärten", "garden", "A1", "Zuhause"],
  ["familie", "Familie", "die", "Familien", "family", "A1", "Menschen"],
  ["kind", "Kind", "das", "Kinder", "child", "A1", "Menschen"],
  ["mann", "Mann", "der", "Männer", "man", "A1", "Menschen"],
  ["frau", "Frau", "die", "Frauen", "woman", "A1", "Menschen"],
  ["maedchen", "Mädchen", "das", "Mädchen", "girl", "A1", "Menschen"],
  ["freund", "Freund", "der", "Freunde", "friend", "A1", "Menschen"],
  ["schwester", "Schwester", "die", "Schwestern", "sister", "A1", "Menschen"],
  ["baby", "Baby", "das", "Babys", "baby", "A1", "Menschen"],
  ["lehrer", "Lehrer", "der", "Lehrer", "teacher", "A1", "Menschen"],
  ["studentin", "Studentin", "die", "Studentinnen", "female student", "A1", "Menschen"],
  ["auto", "Auto", "das", "Autos", "car", "A1", "Unterwegs"],
  ["zug", "Zug", "der", "Züge", "train", "A1", "Unterwegs"],
  ["strasse", "Straße", "die", "Straßen", "street", "A1", "Unterwegs"],
  ["fahrrad", "Fahrrad", "das", "Fahrräder", "bicycle", "A1", "Unterwegs"],
  ["bus", "Bus", "der", "Busse", "bus", "A1", "Unterwegs"],
  ["bahn", "Bahn", "die", "Bahnen", "railway", "A1", "Unterwegs"],
  ["flugzeug", "Flugzeug", "das", "Flugzeuge", "airplane", "A1", "Unterwegs"],
  ["bahnhof", "Bahnhof", "der", "Bahnhöfe", "station", "A1", "Unterwegs"],
  ["reise", "Reise", "die", "Reisen", "journey", "A2", "Unterwegs"],
  ["ticket", "Ticket", "das", "Tickets", "ticket", "A1", "Unterwegs"],
  ["morgen", "Morgen", "der", "Morgen", "morning", "A1", "Zeit"],
  ["woche", "Woche", "die", "Wochen", "week", "A1", "Zeit"],
  ["jahr", "Jahr", "das", "Jahre", "year", "A1", "Zeit"],
  ["monat", "Monat", "der", "Monate", "month", "A1", "Zeit"],
  ["nacht", "Nacht", "die", "Nächte", "night", "A1", "Zeit"],
  ["wochenende", "Wochenende", "das", "Wochenenden", "weekend", "A1", "Zeit"],
  ["tag", "Tag", "der", "Tage", "day", "A1", "Zeit"],
  ["stunde", "Stunde", "die", "Stunden", "hour", "A1", "Zeit"],
  ["datum", "Datum", "das", "Daten", "date", "A2", "Zeit"],
  ["himmel", "Himmel", "der", "Himmel", "sky", "A1", "Natur"],
  ["sonne", "Sonne", "die", "Sonnen", "sun", "A1", "Natur"],
  ["meer", "Meer", "das", "Meere", "sea", "A1", "Natur"],
  ["baum", "Baum", "der", "Bäume", "tree", "A1", "Natur"],
  ["blume", "Blume", "die", "Blumen", "flower", "A1", "Natur"],
  ["tier", "Tier", "das", "Tiere", "animal", "A1", "Natur"],
  ["hund", "Hund", "der", "Hunde", "dog", "A1", "Natur"],
  ["katze", "Katze", "die", "Katzen", "cat", "A1", "Natur"],
  ["pferd", "Pferd", "das", "Pferde", "horse", "A1", "Natur"],
  ["regen", "Regen", "der", "—", "rain", "A1", "Natur"],
  ["arbeit", "Arbeit", "die", "Arbeiten", "work", "A1", "Alltag"],
  ["buero", "Büro", "das", "Büros", "office", "A1", "Alltag"],
  ["computer", "Computer", "der", "Computer", "computer", "A1", "Alltag"],
  ["schule", "Schule", "die", "Schulen", "school", "A1", "Alltag"],
  ["buch", "Buch", "das", "Bücher", "book", "A1", "Alltag"],
  ["bleistift", "Bleistift", "der", "Bleistifte", "pencil", "A1", "Alltag"],
  ["zeitung", "Zeitung", "die", "Zeitungen", "newspaper", "A2", "Alltag"],
  ["handy", "Handy", "das", "Handys", "mobile phone", "A1", "Alltag"],
  ["schluessel", "Schlüssel", "der", "Schlüssel", "key", "A1", "Alltag"],
  ["tasche", "Tasche", "die", "Taschen", "bag", "A1", "Alltag"],
  ["foto", "Foto", "das", "Fotos", "photo", "A1", "Alltag"],
  ["kopf", "Kopf", "der", "Köpfe", "head", "A1", "Körper"],
  ["hand", "Hand", "die", "Hände", "hand", "A1", "Körper"],
  ["auge", "Auge", "das", "Augen", "eye", "A1", "Körper"],
  ["mund", "Mund", "der", "Münder", "mouth", "A1", "Körper"],
  ["nase", "Nase", "die", "Nasen", "nose", "A1", "Körper"],
  ["ohr", "Ohr", "das", "Ohren", "ear", "A1", "Körper"],
  ["arzt", "Arzt", "der", "Ärzte", "doctor", "A1", "Körper"],
  ["gesundheit", "Gesundheit", "die", "—", "health", "A2", "Körper"],
  ["herz", "Herz", "das", "Herzen", "heart", "A1", "Körper"],
  ["saft", "Saft", "der", "Säfte", "juice", "A1", "Essen"],
  ["salat", "Salat", "der", "Salate", "salad", "A1", "Essen"],
  ["reis", "Reis", "der", "—", "rice", "A1", "Essen"],
  ["kuchen", "Kuchen", "der", "Kuchen", "cake", "A1", "Essen"],
  ["zucker", "Zucker", "der", "—", "sugar", "A1", "Essen"],
  ["loeffel", "Löffel", "der", "Löffel", "spoon", "A1", "Essen"],
  ["teller", "Teller", "der", "Teller", "plate", "A1", "Essen"],
  ["kuehlschrank", "Kühlschrank", "der", "Kühlschränke", "refrigerator", "A1", "Zuhause"],
  ["spiegel", "Spiegel", "der", "Spiegel", "mirror", "A1", "Zuhause"],
  ["balkon", "Balkon", "der", "Balkone", "balcony", "A1", "Zuhause"],
  ["boden", "Boden", "der", "Böden", "floor", "A2", "Zuhause"],
  ["ofen", "Ofen", "der", "Öfen", "oven", "A2", "Zuhause"],
  ["teppich", "Teppich", "der", "Teppiche", "carpet", "A2", "Zuhause"],
  ["sohn", "Sohn", "der", "Söhne", "son", "A1", "Menschen"],
  ["bruder", "Bruder", "der", "Brüder", "brother", "A1", "Menschen"],
  ["vater", "Vater", "der", "Väter", "father", "A1", "Menschen"],
  ["opa", "Opa", "der", "Opas", "grandfather", "A1", "Menschen"],
  ["nachbar", "Nachbar", "der", "Nachbarn", "neighbor", "A2", "Menschen"],
  ["fahrer", "Fahrer", "der", "Fahrer", "driver", "A2", "Menschen"],
  ["verkaeufer", "Verkäufer", "der", "Verkäufer", "salesperson", "A2", "Menschen"],
  ["kunde", "Kunde", "der", "Kunden", "customer", "A2", "Menschen"],
  ["flughafen", "Flughafen", "der", "Flughäfen", "airport", "A2", "Unterwegs"],
  ["weg", "Weg", "der", "Wege", "way", "A1", "Unterwegs"],
  ["platz", "Platz", "der", "Plätze", "square", "A1", "Unterwegs"],
  ["verkehr", "Verkehr", "der", "—", "traffic", "A2", "Unterwegs"],
  ["hafen", "Hafen", "der", "Häfen", "harbor", "A2", "Unterwegs"],
  ["urlaub", "Urlaub", "der", "Urlaube", "vacation", "A1", "Unterwegs"],
  ["fruehling", "Frühling", "der", "Frühlinge", "spring", "A1", "Zeit"],
  ["sommer", "Sommer", "der", "Sommer", "summer", "A1", "Zeit"],
  ["herbst", "Herbst", "der", "Herbste", "autumn", "A1", "Zeit"],
  ["winter", "Winter", "der", "Winter", "winter", "A1", "Zeit"],
  ["abend", "Abend", "der", "Abende", "evening", "A1", "Zeit"],
  ["wald", "Wald", "der", "Wälder", "forest", "A1", "Natur"],
  ["berg", "Berg", "der", "Berge", "mountain", "A1", "Natur"],
  ["fluss", "Fluss", "der", "Flüsse", "river", "A1", "Natur"],
  ["see", "See", "der", "Seen", "lake", "A1", "Natur"],
  ["wind", "Wind", "der", "Winde", "wind", "A1", "Natur"],
  ["schnee", "Schnee", "der", "—", "snow", "A1", "Natur"],
  ["vogel", "Vogel", "der", "Vögel", "bird", "A1", "Natur"],
  ["hase", "Hase", "der", "Hasen", "rabbit", "A2", "Natur"],
  ["beruf", "Beruf", "der", "Berufe", "profession", "A1", "Alltag"],
  ["chef", "Chef", "der", "Chefs", "boss", "A2", "Alltag"],
  ["termin", "Termin", "der", "Termine", "appointment", "A2", "Alltag"],
  ["kugelschreiber", "Kugelschreiber", "der", "Kugelschreiber", "pen", "A2", "Alltag"],
  ["bildschirm", "Bildschirm", "der", "Bildschirme", "screen", "A2", "Alltag"],
  ["drucker", "Drucker", "der", "Drucker", "printer", "A2", "Alltag"],
  ["ordner", "Ordner", "der", "Ordner", "folder", "A2", "Alltag"],
  ["fuss", "Fuß", "der", "Füße", "foot", "A1", "Körper"],
  ["arm", "Arm", "der", "Arme", "arm", "A1", "Körper"],
  ["ruecken", "Rücken", "der", "Rücken", "back", "A1", "Körper"],
  ["bauch", "Bauch", "der", "Bäuche", "stomach", "A1", "Körper"],
  ["zahn", "Zahn", "der", "Zähne", "tooth", "A1", "Körper"],
  ["hals", "Hals", "der", "Hälse", "neck", "A1", "Körper"],
  ["orange", "Orange", "die", "Orangen", "orange", "A1", "Essen"],
  ["kartoffel", "Kartoffel", "die", "Kartoffeln", "potato", "A1", "Essen"],
  ["tomate", "Tomate", "die", "Tomaten", "tomato", "A1", "Essen"],
  ["butter", "Butter", "die", "—", "butter", "A1", "Essen"],
  ["gabel", "Gabel", "die", "Gabeln", "fork", "A1", "Essen"],
  ["flasche", "Flasche", "die", "Flaschen", "bottle", "A1", "Essen"],
  ["tasse", "Tasse", "die", "Tassen", "cup", "A1", "Essen"],
  ["schokolade", "Schokolade", "die", "Schokoladen", "chocolate", "A1", "Essen"],
  ["wand", "Wand", "die", "Wände", "wall", "A1", "Zuhause"],
  ["treppe", "Treppe", "die", "Treppen", "stairs", "A2", "Zuhause"],
  ["decke", "Decke", "die", "Decken", "ceiling", "A2", "Zuhause"],
  ["dusche", "Dusche", "die", "Duschen", "shower", "A1", "Zuhause"],
  ["badewanne", "Badewanne", "die", "Badewannen", "bathtub", "A2", "Zuhause"],
  ["garage", "Garage", "die", "Garagen", "garage", "A2", "Zuhause"],
  ["mutter", "Mutter", "die", "Mütter", "mother", "A1", "Menschen"],
  ["tochter", "Tochter", "die", "Töchter", "daughter", "A1", "Menschen"],
  ["oma", "Oma", "die", "Omas", "grandmother", "A1", "Menschen"],
  ["freundin", "Freundin", "die", "Freundinnen", "female friend", "A1", "Menschen"],
  ["nachbarin", "Nachbarin", "die", "Nachbarinnen", "female neighbor", "A2", "Menschen"],
  ["aerztin", "Ärztin", "die", "Ärztinnen", "female doctor", "A2", "Menschen"],
  ["lehrerin", "Lehrerin", "die", "Lehrerinnen", "female teacher", "A1", "Menschen"],
  ["haltestelle", "Haltestelle", "die", "Haltestellen", "stop", "A1", "Unterwegs"],
  ["ampel", "Ampel", "die", "Ampeln", "traffic light", "A1", "Unterwegs"],
  ["bruecke", "Brücke", "die", "Brücken", "bridge", "A2", "Unterwegs"],
  ["kreuzung", "Kreuzung", "die", "Kreuzungen", "intersection", "A2", "Unterwegs"],
  ["ubahn", "U-Bahn", "die", "U-Bahnen", "subway", "A1", "Unterwegs"],
  ["fahrkarte", "Fahrkarte", "die", "Fahrkarten", "travel ticket", "A1", "Unterwegs"],
  ["zeit", "Zeit", "die", "Zeiten", "time", "A1", "Zeit"],
  ["minute", "Minute", "die", "Minuten", "minute", "A1", "Zeit"],
  ["sekunde", "Sekunde", "die", "Sekunden", "second", "A1", "Zeit"],
  ["jahreszeit", "Jahreszeit", "die", "Jahreszeiten", "season", "A2", "Zeit"],
  ["vergangenheit", "Vergangenheit", "die", "—", "past", "A2", "Zeit"],
  ["zukunft", "Zukunft", "die", "—", "future", "A2", "Zeit"],
  ["wolke", "Wolke", "die", "Wolken", "cloud", "A1", "Natur"],
  ["insel", "Insel", "die", "Inseln", "island", "A2", "Natur"],
  ["wiese", "Wiese", "die", "Wiesen", "meadow", "A2", "Natur"],
  ["luft", "Luft", "die", "Lüfte (gehoben)", "air", "A1", "Natur"],
  ["erde", "Erde", "die", "Erden (selten)", "earth", "A1", "Natur"],
  ["maus", "Maus", "die", "Mäuse", "mouse", "A1", "Natur"],
  ["ente", "Ente", "die", "Enten", "duck", "A2", "Natur"],
  ["aufgabe", "Aufgabe", "die", "Aufgaben", "task", "A1", "Alltag"],
  ["pruefung", "Prüfung", "die", "Prüfungen", "exam", "A2", "Alltag"],
  ["antwort", "Antwort", "die", "Antworten", "answer", "A1", "Alltag"],
  ["frage", "Frage", "die", "Fragen", "question", "A1", "Alltag"],
  ["sprache", "Sprache", "die", "Sprachen", "language", "A1", "Alltag"],
  ["pause", "Pause", "die", "Pausen", "break", "A1", "Alltag"],
  ["schulter", "Schulter", "die", "Schultern", "shoulder", "A2", "Körper"],
  ["haut", "Haut", "die", "Häute", "skin", "A2", "Körper"],
  ["apotheke", "Apotheke", "die", "Apotheken", "pharmacy", "A1", "Körper"],
  ["krankheit", "Krankheit", "die", "Krankheiten", "illness", "A2", "Körper"],
  ["medizin", "Medizin", "die", "Medizinen (Arzneien)", "medicine", "A2", "Körper"],
  ["brille", "Brille", "die", "Brillen", "glasses", "A1", "Körper"],
  ["stimme", "Stimme", "die", "Stimmen", "voice", "A2", "Körper"],
  ["fleisch", "Fleisch", "das", "—", "meat", "A1", "Essen"],
  ["gemuese", "Gemüse", "das", "—", "vegetables", "A1", "Essen"],
  ["obst", "Obst", "das", "—", "fruit", "A1", "Essen"],
  ["fruehstueck", "Frühstück", "das", "Frühstücke", "breakfast", "A1", "Essen"],
  ["mittagessen", "Mittagessen", "das", "Mittagessen", "lunch", "A1", "Essen"],
  ["abendessen", "Abendessen", "das", "Abendessen", "dinner", "A1", "Essen"],
  ["salz", "Salz", "das", "Salze (fachsprachlich)", "salt", "A1", "Essen"],
  ["messer", "Messer", "das", "Messer", "knife", "A1", "Essen"],
  ["sofa", "Sofa", "das", "Sofas", "sofa", "A1", "Zuhause"],
  ["bild", "Bild", "das", "Bilder", "picture", "A1", "Zuhause"],
  ["regal", "Regal", "das", "Regale", "shelf", "A2", "Zuhause"],
  ["dach", "Dach", "das", "Dächer", "roof", "A2", "Zuhause"],
  ["badezimmer", "Badezimmer", "das", "Badezimmer", "bathroom", "A1", "Zuhause"],
  ["wohnzimmer", "Wohnzimmer", "das", "Wohnzimmer", "living room", "A1", "Zuhause"],
  ["schlafzimmer", "Schlafzimmer", "das", "Schlafzimmer", "bedroom", "A1", "Zuhause"],
  ["gebaeude", "Gebäude", "das", "Gebäude", "building", "A2", "Zuhause"],
  ["paar", "Paar", "das", "Paare", "couple", "A1", "Menschen"],
  ["gesicht", "Gesicht", "das", "Gesichter", "face", "A1", "Menschen"],
  ["publikum", "Publikum", "das", "Publika", "audience", "B1", "Menschen"],
  ["team", "Team", "das", "Teams", "team", "A2", "Menschen"],
  ["mitglied", "Mitglied", "das", "Mitglieder", "member", "A2", "Menschen"],
  ["hobby", "Hobby", "das", "Hobbys", "hobby", "A1", "Alltag"],
  ["motorrad", "Motorrad", "das", "Motorräder", "motorcycle", "A1", "Unterwegs"],
  ["schiff", "Schiff", "das", "Schiffe", "ship", "A1", "Unterwegs"],
  ["taxi", "Taxi", "das", "Taxis", "taxi", "A1", "Unterwegs"],
  ["boot", "Boot", "das", "Boote", "boat", "A1", "Unterwegs"],
  ["gleis", "Gleis", "das", "Gleise", "track", "A2", "Unterwegs"],
  ["gepaeck", "Gepäck", "das", "—", "luggage", "A1", "Unterwegs"],
  ["ziel", "Ziel", "das", "Ziele", "destination", "A1", "Unterwegs"],
  ["jahrhundert", "Jahrhundert", "das", "Jahrhunderte", "century", "A2", "Zeit"],
  ["geschenk", "Geschenk", "das", "Geschenke", "gift", "A1", "Alltag"],
  ["fest", "Fest", "das", "Feste", "celebration", "A2", "Alltag"],
  ["wetter", "Wetter", "das", "—", "weather", "A1", "Natur"],
  ["gewitter", "Gewitter", "das", "Gewitter", "thunderstorm", "A2", "Natur"],
  ["tal", "Tal", "das", "Täler", "valley", "A2", "Natur"],
  ["ufer", "Ufer", "das", "Ufer", "shore", "A2", "Natur"],
  ["land", "Land", "das", "Länder", "country", "A1", "Natur"],
  ["dorf", "Dorf", "das", "Dörfer", "village", "A1", "Natur"],
  ["blatt", "Blatt", "das", "Blätter", "leaf", "A2", "Natur"],
  ["insekt", "Insekt", "das", "Insekten", "insect", "A2", "Natur"],
  ["heft", "Heft", "das", "Hefte", "notebook", "A1", "Alltag"],
  ["papier", "Papier", "das", "Papiere", "paper", "A1", "Alltag"],
  ["wort", "Wort", "das", "Wörter", "word", "A1", "Alltag"],
  ["beispiel", "Beispiel", "das", "Beispiele", "example", "A1", "Alltag"],
  ["ergebnis", "Ergebnis", "das", "Ergebnisse", "result", "A2", "Alltag"],
  ["problem", "Problem", "das", "Probleme", "problem", "A1", "Alltag"],
  ["thema", "Thema", "das", "Themen", "topic", "A1", "Alltag"],
  ["knie", "Knie", "das", "Knie", "knee", "A1", "Körper"],
  ["bein", "Bein", "das", "Beine", "leg", "A1", "Körper"],
  ["blut", "Blut", "das", "—", "blood", "A2", "Körper"],
  ["medikament", "Medikament", "das", "Medikamente", "medication", "A2", "Körper"],
  ["krankenhaus", "Krankenhaus", "das", "Krankenhäuser", "hospital", "A1", "Körper"],
  ["fieber", "Fieber", "das", "—", "fever", "A2", "Körper"],
].map(([id, word, article, plural, translation, level, topic]) => ({ id, word, article, plural, translation, level, topic })) as Noun[];

export const challengeNouns: Noun[] = [
  ["zusammenhang", "Zusammenhang", "der", "Zusammenhänge", "connection", "B1", "Schwer"],
  ["einfluss", "Einfluss", "der", "Einflüsse", "influence", "B1", "Schwer"],
  ["aufwand", "Aufwand", "der", "Aufwände", "effort", "B2", "Schwer"],
  ["anspruch", "Anspruch", "der", "Ansprüche", "claim", "B2", "Schwer"],
  ["fortschritt", "Fortschritt", "der", "Fortschritte", "progress", "B1", "Schwer"],
  ["rueckgang", "Rückgang", "der", "Rückgänge", "decline", "B2", "Schwer"],
  ["schwerpunkt", "Schwerpunkt", "der", "Schwerpunkte", "focus", "B1", "Schwer"],
  ["wettbewerb", "Wettbewerb", "der", "Wettbewerbe", "competition", "B1", "Schwer"],
  ["widerspruch", "Widerspruch", "der", "Widersprüche", "contradiction", "B2", "Schwer"],
  ["ueberblick", "Überblick", "der", "Überblicke", "overview", "B1", "Schwer"],
  ["erwerb", "Erwerb", "der", "—", "acquisition", "B2", "Schwer"],
  ["nutzen", "Nutzen", "der", "—", "benefit", "B1", "Schwer"],
  ["mangel", "Mangel", "der", "Mängel", "shortage", "B1", "Schwer"],
  ["anlass", "Anlass", "der", "Anlässe", "occasion", "B1", "Schwer"],
  ["umgang", "Umgang", "der", "—", "handling", "B1", "Schwer"],
  ["vorrat", "Vorrat", "der", "Vorräte", "supply", "B1", "Schwer"],
  ["zweifel", "Zweifel", "der", "Zweifel", "doubt", "B1", "Schwer"],
  ["entwurf", "Entwurf", "der", "Entwürfe", "draft", "B1", "Schwer"],
  ["zeitraum", "Zeitraum", "der", "Zeiträume", "period", "B1", "Schwer"],
  ["bestandteil", "Bestandteil", "der", "Bestandteile", "component", "B2", "Schwer"],
  ["voraussetzung", "Voraussetzung", "die", "Voraussetzungen", "prerequisite", "B1", "Schwer"],
  ["herausforderung", "Herausforderung", "die", "Herausforderungen", "challenge", "B1", "Schwer"],
  ["erkenntnis", "Erkenntnis", "die", "Erkenntnisse", "insight", "B2", "Schwer"],
  ["gewohnheit", "Gewohnheit", "die", "Gewohnheiten", "habit", "B1", "Schwer"],
  ["gelegenheit", "Gelegenheit", "die", "Gelegenheiten", "opportunity", "B1", "Schwer"],
  ["massnahme", "Maßnahme", "die", "Maßnahmen", "measure", "B2", "Schwer"],
  ["auswirkung", "Auswirkung", "die", "Auswirkungen", "effect", "B1", "Schwer"],
  ["umgebung", "Umgebung", "die", "Umgebungen", "surroundings", "B1", "Schwer"],
  ["verfuegbarkeit", "Verfügbarkeit", "die", "—", "availability", "B2", "Schwer"],
  ["wahrnehmung", "Wahrnehmung", "die", "Wahrnehmungen", "perception", "B2", "Schwer"],
  ["ruecksicht", "Rücksicht", "die", "—", "consideration", "B1", "Schwer"],
  ["sehnsucht", "Sehnsucht", "die", "Sehnsüchte", "longing", "B1", "Schwer"],
  ["zuversicht", "Zuversicht", "die", "—", "confidence", "B2", "Schwer"],
  ["befugnis", "Befugnis", "die", "Befugnisse", "authority", "B2", "Schwer"],
  ["abweichung", "Abweichung", "die", "Abweichungen", "deviation", "B2", "Schwer"],
  ["auseinandersetzung", "Auseinandersetzung", "die", "Auseinandersetzungen", "dispute", "B2", "Schwer"],
  ["vorgehensweise", "Vorgehensweise", "die", "Vorgehensweisen", "approach", "B2", "Schwer"],
  ["notwendigkeit", "Notwendigkeit", "die", "Notwendigkeiten", "necessity", "B2", "Schwer"],
  ["beschaffenheit", "Beschaffenheit", "die", "—", "condition", "B2", "Schwer"],
  ["verantwortung", "Verantwortung", "die", "—", "responsibility", "B1", "Schwer"],
  ["verhaeltnis", "Verhältnis", "das", "Verhältnisse", "relationship", "B1", "Schwer"],
  ["verhalten", "Verhalten", "das", "—", "behavior", "B1", "Schwer"],
  ["ereignis", "Ereignis", "das", "Ereignisse", "event", "B1", "Schwer"],
  ["beduerfnis", "Bedürfnis", "das", "Bedürfnisse", "need", "B1", "Schwer"],
  ["hindernis", "Hindernis", "das", "Hindernisse", "obstacle", "B1", "Schwer"],
  ["merkmal", "Merkmal", "das", "Merkmale", "characteristic", "B1", "Schwer"],
  ["verfahren", "Verfahren", "das", "Verfahren", "procedure", "B2", "Schwer"],
  ["vorhaben", "Vorhaben", "das", "Vorhaben", "project", "B2", "Schwer"],
  ["vermoegen", "Vermögen", "das", "Vermögen", "assets", "B2", "Schwer"],
  ["bewusstsein", "Bewusstsein", "das", "—", "awareness", "B2", "Schwer"],
  ["umfeld", "Umfeld", "das", "Umfelder", "environment", "B1", "Schwer"],
  ["ausmass", "Ausmaß", "das", "Ausmaße", "extent", "B2", "Schwer"],
  ["anliegen", "Anliegen", "das", "Anliegen", "concern", "B2", "Schwer"],
  ["gutachten", "Gutachten", "das", "Gutachten", "expert opinion", "B2", "Schwer"],
  ["missverstaendnis", "Missverständnis", "das", "Missverständnisse", "misunderstanding", "B1", "Schwer"],
  ["zugestaendnis", "Zugeständnis", "das", "Zugeständnisse", "concession", "B2", "Schwer"],
  ["erscheinungsbild", "Erscheinungsbild", "das", "Erscheinungsbilder", "appearance", "B2", "Schwer"],
  ["einverstaendnis", "Einverständnis", "das", "—", "consent", "B2", "Schwer"],
  ["gleichgewicht", "Gleichgewicht", "das", "Gleichgewichte", "balance", "B1", "Schwer"],
  ["durcheinander", "Durcheinander", "das", "—", "confusion", "B1", "Schwer"],
].map(([id, word, article, plural, translation, level, topic]) => ({ id, word, article, plural, translation, level, topic })) as Noun[];

export const allNouns = [...nouns, ...challengeNouns];

export type CategoryId = "all" | "life" | "people" | "travel" | "nature" | "challenge";

export const nounCategories: Array<{ id: CategoryId; label: string; description: string }> = [
  { id: "all", label: "Alle Basiswörter", description: "Der / Die / Das · Nominativ" },
  { id: "life", label: "Essen & Zuhause", description: "Dinge aus Küche und Wohnung" },
  { id: "people", label: "Menschen & Körper", description: "Familie, Berufe und Gesundheit" },
  { id: "travel", label: "Unterwegs & Zeit", description: "Reisen, Verkehr und Kalender" },
  { id: "nature", label: "Natur & Alltag", description: "Umwelt, Lernen und Arbeit" },
  { id: "challenge", label: "Schwer & selten", description: "60 zusätzliche Wörter · B1–B2" },
];

export function nounsForCategory(category: CategoryId): Noun[] {
  if (category === "challenge") return challengeNouns;
  if (category === "life") return nouns.filter((noun) => noun.topic === "Essen" || noun.topic === "Zuhause");
  if (category === "people") return nouns.filter((noun) => noun.topic === "Menschen" || noun.topic === "Körper");
  if (category === "travel") return nouns.filter((noun) => noun.topic === "Unterwegs" || noun.topic === "Zeit");
  if (category === "nature") return nouns.filter((noun) => noun.topic === "Natur" || noun.topic === "Alltag");
  return nouns;
}

export function isCategoryId(value: unknown): value is CategoryId {
  return nounCategories.some((category) => category.id === value);
}

export const nounById = new Map(allNouns.map((noun) => [noun.id, noun]));
